### PR TITLE
Improve default caching

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
Part of Kdyby/Annotations#7, not ready to merge yet.

**Comment by enumag** [comment]
**Need to tag new Kdyby/DoctrineCache and increase required version before merging.**

**Comment by fprochazka** [comment]
If you wanna change the default impl, you should also change the impl of annotation reader to use the `FileCacheReader `

**Comment by enumag** [comment]
Actually no. FileCacheReader is deprecated in favor of CachedReader + FilesystemCache.

**Comment by fprochazka** [comment]
@enumag I see. Does it have solved invalidation like my `default` has?

**Comment by enumag** [comment]
I think so, but I'll check it to be sure. We can't merge this yet anyway.

**Pull request closed without merging**
