### PR TITLE
Fix compatibility with Nette 2.4

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by fprochazka** [comment]
The tests have failed, will you please fix it?

**Comment by fprochazka** [comment]
Ah, now that I think about it, it probably just needs time for packagist to catch up.

**Comment by fprochazka** [comment]
@enumag btw, not a very good branch name :)

**Comment by enumag** [comment]
Yeah well the branch is just temporary anyway so I didn't bother. :-)

I'll be AFK until night. This should pass eventually with a restart though.

**Comment by fprochazka** [comment]
Looks like it passed.

**Pull request merged**
